package rules.example.rfid.vo
import com.example.rfid.vo.TransportInfoVO
import com.example.rfid.vo.TransportVO
import com.example.rfid.bl.RuleEngine.RuleAction
dialect "java"
global RuleAction ruleAction;
rule "test"
    when
        $p : TransportInfoVO(ip == "192.168.1.1" && num > 20 && state == 1 && name == "123")
    then
        TransportVO transportVO = new TransportVO();
        transportVO.setCAS_id($p.getCasId());
        ruleAction.log(transportVO);
end
